#!/bin/bash

config=~/.config/github-cli

#check config file
test [ ! -f $config ] && echo 'config not found' && exit 1

# check repo name exist
test -z $1 && echo "Repo name required." 1>&2 && exit 1

#require config
source $config

# get repo name
repoName=$1

echo 'create github repositries "'$username/$repoName'"'
echo '...'

# send api create repo github
curl -v -H "Authorization: token $token" https://api.github.com/user/repos -d '{"name":"$repoName"}'

while [ true ]; do
  read -p "Init git local and remote [ssh/https]? (s/h/n): " next

  if [ "$next" = "s" ]; then
    mkdir $repoName
    cd $repoName
    git init
    git remote add origin 'git@github.com:'$username/$repoName'.git'
    echo 'adding remote origin...'
    git config --get remote.origin.url
    exit 0
  fi

  if [ "$next" = "h" ]; then
    mkdir $repoName
    cd $repoName
    git init
    git remote add origin 'https://github.com/'$username/$repoName'.git'
    echo 'adding remote origin...'
    git config --get remote.origin.url
    exit 0
  fi

  if [ "$next" = "n" ]; then
    echo 'Canceled'
    exit 0
  fi

  echo 'input only (s/h/n)'

done