#!/bin/bash
#
# Get current path
currentPath="$(dirname "$(readlink -f "$0")")"

case $1 in
  create)
    sh $currentPath/create-repo $2 $3 $4 $5 $6 $7
    ;;
  *)
    echo "Sorry, I don't understand"
    ;;
esac